// GENERATED by `slab gen wc` — do not edit.

/** Metadata captured for every emitted signal. */
export interface SignalMeta {
   readonly x: number;
   readonly y: number;
   readonly dx: number;
   readonly dy: number;
   readonly drag_dx: number;
   readonly drag_dy: number;
   readonly mods: number;
   readonly button: number;
   readonly clicks: number;
   readonly key: string;
   readonly src_key: string;
   readonly src_item: string;
   readonly cancelled: boolean;
   readonly dropped: boolean;
}
/** Detail carried by non-text signal CustomEvents. */
export interface SignalDetail {
   readonly item: string;
   readonly meta: SignalMeta;
}
/** Detail carried by Change, Submit, and Resize CustomEvents. */
export interface TextSignalDetail extends SignalDetail {
   readonly text: string;
}

/** One retained scene entry returned by `sceneSnapshot()`. */
export interface SceneNode {
   key: string;
   node: number;
   parent: number;
   kind: number;
   x: number;
   y: number;
   w: number;
   h: number;
   radius: number;
   rotation: number;
   cx: number;
   cy: number;
   flags: number;
   content_main: number;
   scroll_off: number;
   is_row: boolean;
   scroll: boolean;
   src_line: number;
   scroll_cross: number;
   content_cross: number;
   role: string;
   label: string;
   desc: string;
   checked: boolean | 'mixed' | null;
   expanded: boolean | null;
   selected: boolean | null;
   active_descendant: string;
   controls: string;
   value_now: number | null;
   value_min: number | null;
   value_max: number | null;
   value_text: string;
   modal: boolean | null;
   live: 'off' | 'polite' | 'assertive' | null;
   live_atomic: boolean | null;
   level: number | null;
   pos_in_set: number | null;
   set_size: number | null;
   disabled: boolean;
   focused: boolean;
}

export interface SpeciesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "picked"?: boolean;
}

export interface ClassesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "picked"?: boolean;
}

export interface BackgroundsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "picked"?: boolean;
}

export declare class SlabForgeElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'species'(): SpeciesItem[];
   set 'species'(v: SpeciesItem[]);
   get 'classes'(): ClassesItem[];
   set 'classes'(v: ClassesItem[]);
   get 'backgrounds'(): BackgroundsItem[];
   set 'backgrounds'(v: BackgroundsItem[]);
   get 'species_count'(): string | undefined;
   set 'species_count'(v: string);
   get 'classes_count'(): string | undefined;
   set 'classes_count'(v: string);
   get 'backgrounds_count'(): string | undefined;
   set 'backgrounds_count'(v: string);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabPickElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'name'(): string | undefined;
   set 'name'(v: string);
   get 'picked'(): boolean | undefined;
   set 'picked'(v: boolean);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

/** Signal CustomEvent names → detail types. */
export declare const signals: {
   readonly 'filter': TextSignalDetail;
   readonly 'pick': SignalDetail;
   readonly 'generate': SignalDetail;
};

declare global {
   interface HTMLElementTagNameMap {
      'gl-forge': SlabForgeElement;
      'slab-pick': SlabPickElement;
   }
}
