// GENERATED by `slab gen wc` — do not edit.

/** Metadata captured for every emitted signal. */
export interface SignalMeta {
   readonly x: number;
   readonly y: number;
   readonly dx: number;
   readonly dy: number;
   readonly drag_dx: number;
   readonly drag_dy: number;
   readonly mods: number;
   readonly button: number;
   readonly clicks: number;
   readonly key: string;
   readonly src_key: string;
   readonly src_item: string;
   readonly cancelled: boolean;
   readonly dropped: boolean;
}
/** Detail carried by non-text signal CustomEvents. */
export interface SignalDetail {
   readonly item: string;
   readonly meta: SignalMeta;
}
/** Detail carried by Change, Submit, and Resize CustomEvents. */
export interface TextSignalDetail extends SignalDetail {
   readonly text: string;
}

/** One retained scene entry returned by `sceneSnapshot()`. */
export interface SceneNode {
   key: string;
   node: number;
   parent: number;
   kind: number;
   x: number;
   y: number;
   w: number;
   h: number;
   radius: number;
   rotation: number;
   cx: number;
   cy: number;
   flags: number;
   content_main: number;
   scroll_off: number;
   is_row: boolean;
   scroll: boolean;
   src_line: number;
   scroll_cross: number;
   content_cross: number;
   role: string;
   label: string;
   desc: string;
   checked: boolean | 'mixed' | null;
   expanded: boolean | null;
   selected: boolean | null;
   active_descendant: string;
   controls: string;
   value_now: number | null;
   value_min: number | null;
   value_max: number | null;
   value_text: string;
   modal: boolean | null;
   live: 'off' | 'polite' | 'assertive' | null;
   live_atomic: boolean | null;
   level: number | null;
   pos_in_set: number | null;
   set_size: number | null;
   disabled: boolean;
   focused: boolean;
}

export interface ChipsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "glyph"?: string;
   "show_glyph"?: boolean;
   "symbol"?: string;
   "caption"?: string;
   "value"?: string;
   "kind"?: string;
   "show_mark"?: boolean;
   "has_body"?: boolean;
}

export interface ScoresItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "glyph"?: string;
   "caption"?: string;
   "value"?: string;
   "mod"?: string;
}

export interface SkillsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "attr"?: string;
   "bonus"?: string;
   "prof"?: boolean;
   "expert"?: boolean;
}

export interface SavesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "bonus"?: string;
   "prof"?: boolean;
   "expert"?: boolean;
}

export interface AttacksItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "base"?: string;
   "prof"?: string;
}

export interface ListsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "title"?: string;
   "items"?: ListsItemsItem[];
}

export interface ListsItemsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "body"?: string;
}

export interface MagicItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "glyph"?: string;
   "show_glyph"?: boolean;
   "symbol"?: string;
   "caption"?: string;
   "value"?: string;
   "kind"?: string;
   "show_mark"?: boolean;
   "has_body"?: boolean;
}

export interface SlotsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "rows"?: SlotsRowsItem[];
}

export interface SlotsRowsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "cells"?: SlotsRowsCellsItem[];
}

export interface SlotsRowsCellsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: SlotsRowsCellsRunsItem[];
}

export interface SlotsRowsCellsRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface SlotNotesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: SlotNotesRunsItem[];
}

export interface SlotNotesRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface SpellsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "title"?: string;
   "names"?: SpellsNamesItem[];
}

export interface SpellsNamesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "body"?: string;
}

export interface SectionsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "glyph"?: string;
   "show_glyph"?: boolean;
   "numeral"?: string;
   "has_numeral"?: boolean;
   "title"?: string;
   "show_title"?: boolean;
   "blocks"?: SectionsBlocksItem[];
}

export interface SectionsBlocksItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "heading"?: string;
   "has_heading"?: boolean;
   "has_flavor"?: boolean;
   "has_paras"?: boolean;
   "has_bullets"?: boolean;
   "has_tables"?: boolean;
   "has_notes"?: boolean;
   "has_children"?: boolean;
   "flavor"?: SectionsBlocksFlavorItem[];
   "paras"?: SectionsBlocksFlavorItem[];
   "bullets"?: SectionsBlocksFlavorItem[];
   "tables"?: SectionsBlocksTablesItem[];
   "notes"?: SectionsBlocksFlavorItem[];
   "entries"?: SectionsBlocksEntriesItem[];
   "seal"?: boolean;
}

export interface SectionsBlocksFlavorItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: SectionsBlocksFlavorRunsItem[];
}

export interface SectionsBlocksFlavorRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface SectionsBlocksTablesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "rows"?: SectionsBlocksTablesRowsItem[];
}

export interface SectionsBlocksTablesRowsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "cells"?: SectionsBlocksFlavorItem[];
}

export interface SectionsBlocksEntriesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "sub"?: string;
   "has_name"?: boolean;
   "has_sub"?: boolean;
   "has_flavor"?: boolean;
   "has_paras"?: boolean;
   "has_bullets"?: boolean;
   "has_children"?: boolean;
   "flavor"?: SectionsBlocksFlavorItem[];
   "paras"?: SectionsBlocksFlavorItem[];
   "bullets"?: SectionsBlocksFlavorItem[];
   "entries"?: SectionsBlocksEntriesItem[];
}

export declare class SlabSheetbodyElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'name'(): string | undefined;
   set 'name'(v: string);
   get 'has_name'(): boolean | undefined;
   set 'has_name'(v: boolean);
   get 'title'(): string | undefined;
   set 'title'(v: string);
   get 'has_title'(): boolean | undefined;
   set 'has_title'(v: boolean);
   get 'show_seal'(): boolean | undefined;
   set 'show_seal'(v: boolean);
   get 'has_chips'(): boolean | undefined;
   set 'has_chips'(v: boolean);
   get 'has_scores'(): boolean | undefined;
   set 'has_scores'(v: boolean);
   get 'has_skills'(): boolean | undefined;
   set 'has_skills'(v: boolean);
   get 'has_saves'(): boolean | undefined;
   set 'has_saves'(v: boolean);
   get 'has_attacks'(): boolean | undefined;
   set 'has_attacks'(v: boolean);
   get 'has_lists'(): boolean | undefined;
   set 'has_lists'(v: boolean);
   get 'has_magic'(): boolean | undefined;
   set 'has_magic'(v: boolean);
   get 'has_slots'(): boolean | undefined;
   set 'has_slots'(v: boolean);
   get 'has_spells'(): boolean | undefined;
   set 'has_spells'(v: boolean);
   get 'chips'(): ChipsItem[];
   set 'chips'(v: ChipsItem[]);
   get 'scores'(): ScoresItem[];
   set 'scores'(v: ScoresItem[]);
   get 'skills'(): SkillsItem[];
   set 'skills'(v: SkillsItem[]);
   get 'passive'(): string | undefined;
   set 'passive'(v: string);
   get 'saves'(): SavesItem[];
   set 'saves'(v: SavesItem[]);
   get 'attacks'(): AttacksItem[];
   set 'attacks'(v: AttacksItem[]);
   get 'lists'(): ListsItem[];
   set 'lists'(v: ListsItem[]);
   get 'magic'(): MagicItem[];
   set 'magic'(v: MagicItem[]);
   get 'slots'(): SlotsItem[];
   set 'slots'(v: SlotsItem[]);
   get 'slots_title'(): string | undefined;
   set 'slots_title'(v: string);
   get 'slot_notes'(): SlotNotesItem[];
   set 'slot_notes'(v: SlotNotesItem[]);
   get 'spells'(): SpellsItem[];
   set 'spells'(v: SpellsItem[]);
   get 'sections'(): SectionsItem[];
   set 'sections'(v: SectionsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabRunElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'content'(): string | undefined;
   set 'content'(v: string);
   get 'bold'(): boolean | undefined;
   set 'bold'(v: boolean);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface RunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export declare class SlabParaElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'runs'(): RunsItem[];
   set 'runs'(v: RunsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabFlavorParaElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'runs'(): RunsItem[];
   set 'runs'(v: RunsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabBulletElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'runs'(): RunsItem[];
   set 'runs'(v: RunsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabCellElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'runs'(): RunsItem[];
   set 'runs'(v: RunsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface CellsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: CellsRunsItem[];
}

export interface CellsRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export declare class SlabRowElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'cells'(): CellsItem[];
   set 'cells'(v: CellsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface RowsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "cells"?: RowsCellsItem[];
}

export interface RowsCellsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: RowsCellsRunsItem[];
}

export interface RowsCellsRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export declare class SlabTableElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'rows'(): RowsItem[];
   set 'rows'(v: RowsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabChipElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'glyph'(): string | undefined;
   set 'glyph'(v: string);
   get 'show_glyph'(): boolean | undefined;
   set 'show_glyph'(v: boolean);
   get 'symbol'(): string | undefined;
   set 'symbol'(v: string);
   get 'caption'(): string | undefined;
   set 'caption'(v: string);
   get 'value'(): string | undefined;
   set 'value'(v: string);
   get 'kind'(): string | undefined;
   set 'kind'(v: string);
   get 'show_mark'(): boolean | undefined;
   set 'show_mark'(v: boolean);
   get 'has_body'(): boolean | undefined;
   set 'has_body'(v: boolean);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabScoreElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'glyph'(): string | undefined;
   set 'glyph'(v: string);
   get 'caption'(): string | undefined;
   set 'caption'(v: string);
   get 'value'(): string | undefined;
   set 'value'(v: string);
   get 'mod'(): string | undefined;
   set 'mod'(v: string);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabSkillElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'name'(): string | undefined;
   set 'name'(v: string);
   get 'attr'(): string | undefined;
   set 'attr'(v: string);
   get 'bonus'(): string | undefined;
   set 'bonus'(v: string);
   get 'prof'(): boolean | undefined;
   set 'prof'(v: boolean);
   get 'expert'(): boolean | undefined;
   set 'expert'(v: boolean);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabSaveElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'name'(): string | undefined;
   set 'name'(v: string);
   get 'bonus'(): string | undefined;
   set 'bonus'(v: string);
   get 'prof'(): boolean | undefined;
   set 'prof'(v: boolean);
   get 'expert'(): boolean | undefined;
   set 'expert'(v: boolean);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabAttackElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'name'(): string | undefined;
   set 'name'(v: string);
   get 'base'(): string | undefined;
   set 'base'(v: string);
   get 'prof'(): string | undefined;
   set 'prof'(v: string);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabAttackHeadElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export declare class SlabNamedItemElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'body'(): string | undefined;
   set 'body'(v: string);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface ItemsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "body"?: string;
}

export declare class SlabNamedListElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'title'(): string | undefined;
   set 'title'(v: string);
   get 'items'(): ItemsItem[];
   set 'items'(v: ItemsItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface NamesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "body"?: string;
}

export declare class SlabSpellGroupElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'title'(): string | undefined;
   set 'title'(v: string);
   get 'names'(): NamesItem[];
   set 'names'(v: NamesItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface FlavorItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: FlavorRunsItem[];
}

export interface FlavorRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface ParasItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: ParasRunsItem[];
}

export interface ParasRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface BulletsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: BulletsRunsItem[];
}

export interface BulletsRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface EntriesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "sub"?: string;
   "has_name"?: boolean;
   "has_sub"?: boolean;
   "has_flavor"?: boolean;
   "has_paras"?: boolean;
   "has_bullets"?: boolean;
   "has_children"?: boolean;
   "flavor"?: EntriesFlavorItem[];
   "paras"?: EntriesFlavorItem[];
   "bullets"?: EntriesFlavorItem[];
   "entries"?: EntriesItem[];
}

export interface EntriesFlavorItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: EntriesFlavorRunsItem[];
}

export interface EntriesFlavorRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export declare class SlabEntryElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'name'(): string | undefined;
   set 'name'(v: string);
   get 'sub'(): string | undefined;
   set 'sub'(v: string);
   get 'has_name'(): boolean | undefined;
   set 'has_name'(v: boolean);
   get 'has_sub'(): boolean | undefined;
   set 'has_sub'(v: boolean);
   get 'has_flavor'(): boolean | undefined;
   set 'has_flavor'(v: boolean);
   get 'has_paras'(): boolean | undefined;
   set 'has_paras'(v: boolean);
   get 'has_bullets'(): boolean | undefined;
   set 'has_bullets'(v: boolean);
   get 'has_children'(): boolean | undefined;
   set 'has_children'(v: boolean);
   get 'flavor'(): FlavorItem[];
   set 'flavor'(v: FlavorItem[]);
   get 'paras'(): ParasItem[];
   set 'paras'(v: ParasItem[]);
   get 'bullets'(): BulletsItem[];
   set 'bullets'(v: BulletsItem[]);
   get 'entries'(): EntriesItem[];
   set 'entries'(v: EntriesItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface TablesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "rows"?: TablesRowsItem[];
}

export interface TablesRowsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "cells"?: TablesRowsCellsItem[];
}

export interface TablesRowsCellsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: TablesRowsCellsRunsItem[];
}

export interface TablesRowsCellsRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface NotesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: NotesRunsItem[];
}

export interface NotesRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export declare class SlabBlockElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'heading'(): string | undefined;
   set 'heading'(v: string);
   get 'has_heading'(): boolean | undefined;
   set 'has_heading'(v: boolean);
   get 'has_flavor'(): boolean | undefined;
   set 'has_flavor'(v: boolean);
   get 'has_paras'(): boolean | undefined;
   set 'has_paras'(v: boolean);
   get 'has_bullets'(): boolean | undefined;
   set 'has_bullets'(v: boolean);
   get 'has_tables'(): boolean | undefined;
   set 'has_tables'(v: boolean);
   get 'has_notes'(): boolean | undefined;
   set 'has_notes'(v: boolean);
   get 'has_children'(): boolean | undefined;
   set 'has_children'(v: boolean);
   get 'flavor'(): FlavorItem[];
   set 'flavor'(v: FlavorItem[]);
   get 'paras'(): ParasItem[];
   set 'paras'(v: ParasItem[]);
   get 'bullets'(): BulletsItem[];
   set 'bullets'(v: BulletsItem[]);
   get 'tables'(): TablesItem[];
   set 'tables'(v: TablesItem[]);
   get 'notes'(): NotesItem[];
   set 'notes'(v: NotesItem[]);
   get 'entries'(): EntriesItem[];
   set 'entries'(v: EntriesItem[]);
   get 'seal'(): boolean | undefined;
   set 'seal'(v: boolean);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

export interface BlocksItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "heading"?: string;
   "has_heading"?: boolean;
   "has_flavor"?: boolean;
   "has_paras"?: boolean;
   "has_bullets"?: boolean;
   "has_tables"?: boolean;
   "has_notes"?: boolean;
   "has_children"?: boolean;
   "flavor"?: BlocksFlavorItem[];
   "paras"?: BlocksFlavorItem[];
   "bullets"?: BlocksFlavorItem[];
   "tables"?: BlocksTablesItem[];
   "notes"?: BlocksFlavorItem[];
   "entries"?: BlocksEntriesItem[];
   "seal"?: boolean;
}

export interface BlocksFlavorItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "runs"?: BlocksFlavorRunsItem[];
}

export interface BlocksFlavorRunsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "content"?: string;
   "bold"?: boolean;
}

export interface BlocksTablesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "rows"?: BlocksTablesRowsItem[];
}

export interface BlocksTablesRowsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "cells"?: BlocksFlavorItem[];
}

export interface BlocksEntriesItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "sub"?: string;
   "has_name"?: boolean;
   "has_sub"?: boolean;
   "has_flavor"?: boolean;
   "has_paras"?: boolean;
   "has_bullets"?: boolean;
   "has_children"?: boolean;
   "flavor"?: BlocksFlavorItem[];
   "paras"?: BlocksFlavorItem[];
   "bullets"?: BlocksFlavorItem[];
   "entries"?: BlocksEntriesItem[];
}

export declare class SlabSectionElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'glyph'(): string | undefined;
   set 'glyph'(v: string);
   get 'show_glyph'(): boolean | undefined;
   set 'show_glyph'(v: boolean);
   get 'numeral'(): string | undefined;
   set 'numeral'(v: string);
   get 'has_numeral'(): boolean | undefined;
   set 'has_numeral'(v: boolean);
   get 'title'(): string | undefined;
   set 'title'(v: string);
   get 'show_title'(): boolean | undefined;
   set 'show_title'(v: boolean);
   get 'blocks'(): BlocksItem[];
   set 'blocks'(v: BlocksItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

/** Signal CustomEvent names → detail types. */
export declare const signals: {
};

declare global {
   interface HTMLElementTagNameMap {
      'gl-sheetbody': SlabSheetbodyElement;
      'slab-run': SlabRunElement;
      'slab-para': SlabParaElement;
      'slab-flavor-para': SlabFlavorParaElement;
      'slab-bullet': SlabBulletElement;
      'slab-cell': SlabCellElement;
      'slab-row': SlabRowElement;
      'slab-table': SlabTableElement;
      'slab-chip': SlabChipElement;
      'slab-score': SlabScoreElement;
      'slab-skill': SlabSkillElement;
      'slab-save': SlabSaveElement;
      'slab-attack': SlabAttackElement;
      'slab-attack-head': SlabAttackHeadElement;
      'slab-named-item': SlabNamedItemElement;
      'slab-named-list': SlabNamedListElement;
      'slab-spell-group': SlabSpellGroupElement;
      'slab-entry': SlabEntryElement;
      'slab-block': SlabBlockElement;
      'slab-section': SlabSectionElement;
   }
}
